### ISSUE TITLE
Create a Slack team (or some kind of communication) for the repo

### ISSUE THREAD

**Issue by pseudoramble** [fp-challenges/fp-challenges#8]
It might be nice to have a central place to come talk about fp-challenges. It could range from pitching new problems, working on solving existing problems, or just general Q/A. 

I'd be open to having it on any platform (doesn't have to be Slack). Any thoughts on this?

**Comment by rakis** [comment]
I like the idea of a Slack (or a Discord). Worst case is we do some sorta migration if we hit some platform limitations. I think it would also be nice to figure out the best way to chat about solutions in an elegant way.

**Comment by bitspace** [comment]
I've been using IRC for exactly such conversations for a long time, but Slack really is just a less open IRC replacement, and we use Slack already for other things, so Slack probably makes the most sense.

**Comment by pseudoramble** [comment]
Yeah. The PR setup doesn't work as well as I had hoped mainly because while it gives you a nice view on Github, it doesn't let you merge or share that work effectively. 

Slack seems like a decent way to go (although Discord sounds appealing to just cause I've never used it). If we use Slack though, we may be able to make of use of something like https://memo.ai/ for sharing code snippets and keeping notes on solutions.

**Comment by pseudoramble** [comment]
Does somebody want to set something up?

**Comment by bitspace** [comment]
Do we want to use a @libertymutual.com slack or something separate? I've had a slack team of my own for years that hasn't ever been used.

**Comment by pseudoramble** [comment]
@bitspace I would say separate since we want to encourage anyone to participate and contribute.

**Comment by pseudoramble** [comment]
I put together https://fp-challenges.slack.com for us to try for the time being. Join up!

(This invite link will self-destruct in 1-week). https://fp-challenges.slack.com/shared_invite/MTY5Mjc0ODIxMTI0LTE0OTIxMzMzODgtNzY3YTVlMDc4ZQ

**Comment by pseudoramble** [comment]
Also seems like we need to set up a way for anyone to sign into it instead of just manual invites. There are some tools out there that attempt to provide that ability.

**Comment by rakis** [comment]
Added this to send out invites, we can probably update the README to reflect this.
http://fp-challenges-slack.herokuapp.com/

**Comment by pseudoramble** [comment]
Gonna call this all good now that we've got our signup form in place!
